services:
  dev-quintal:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true  # Enable polling for hot reload in Docker
    command: npm run dev
    restart: unless-stopped
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
