services:
  ux-web:
    container_name: ${UX_APP}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    restart: unless-stopped
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
