services:
  quintal:
    container_name: quintal
    build:
      context: $PROD_PATH
      dockerfile: $PROD_PATH/docker/pre-producao/Dockerfile
    env_file:
      - $PROD_PATH/.env
    ports:
      - "83:3000"
    restart: unless-stopped
    networks:
      - app_network
    volumes:
      - $PROD_PATH/prisma:/app/prisma

networks:
  app_network:
    driver: bridge
