services:
  quintal:
    container_name: quintal
    build:
      context: $DEV_PATH
      dockerfile: $DEV_PATH/docker/pre-producao/Dockerfile
    env_file:
      - $DEV_PATH/.env
    ports:
      - "83:3000"
    restart: unless-stopped
    networks:
      - app_network
    volumes:
      - $DEV_PATH/prisma:/app/prisma

networks:
  app_network:
    driver: bridge
