name: Cozinhando o final

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  cozinhando:
    name: Cozinhando para producao
    runs-on: ubuntu-latest
    steps:
      - name: Sincronizando repositorio
        uses: actions/checkout@v4
      - name: Cozinhando (npm install & build)
        run: |
          npm install
          npm run build --if-present
      - name: Guardando o que foi cozido
        uses: actions/upload-artifact@v4
        with:
            name: cozido
            path: dist
