name: Cozinhando

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  cozinhando:
    name: Cozinhando nossa app
    runs-on: ubuntu-latest
    steps:
      - name: Sincronizar repositorio
        uses: actions/checkout@v4
      - name: npm install e build
        run: |
          npm install
          npm run build --if-present
      - name: Guardando o que foi cozido
        uses: actions/upload-artifact@v4
        with:
            name: cozido
            path: dist
