name: Cozinhando pra amostrar

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  cozinhando:
    name: Cozinhando (build)
    runs-on: ubuntu-latest
    steps:
      - name: Sincronizando repositorio
        uses: actions/checkout@v4
      - name: Cozinhando (npm install & build)
        run: |
          npm install
          npm run build --if-present
      - name: Guardando o que foi cozido
        uses: actions/upload-artifact@v4
        with:
            name: cozido
            path: dist
  baixar:
    name: Baixando o cozido
    environment: Quintal
    runs-on: ubuntu-latest
    needs: cozinhando
    steps:
      - name: Baixando o que foi cozido
        uses: actions/download-artifact@v4
        with:
          name: cozido
          path: dist
      - name: Copiando para o servidor
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: dist/*
          target: ${{ secrets.PATH }}
  deploy:
    name: Servindo
    environment: Quintal
    needs: baixar
    runs-on: ubuntu-latest
    steps:
      - name: Servindo o cozido
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd $PRODUCAO
            mv dist app
