name: Cozinhando o Desenvolvimento

on:
  push:
    branches:
      - deselvolvimento
  workflow_dispatch:

jobs:
  cozinhando:
    name: Cozinhando para testar (build)
    runs-on: ubuntu-latest
    steps:
      - name: Sincronizando repositorio
        uses: actions/checkout@v4
      - name: Cozinhando (npm install & build)
        run: |
          npm install
          npm run build --if-present
      - name: Guardando o que foi cozido
        uses: actions/upload-artifact@v4
        with:
            name: cozido
            path: dist
  baixar:
    name: Baixando o cozido
    environment: Patio
    runs-on: ubuntu-latest
    needs: cozinhando
    steps:
      - name: Baixando o que foi cozido
        uses: actions/download-artifact@v4
        with:
          name: cozido
          path: dist
      - name: Copiando para o servidor
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: dist/*
          target: ${{ secrets.PATH }}
  deploy:
    name: Servindo para testar
    environment: Patio
    needs: baixar
    runs-on: ubuntu-latest
    steps:
      - name: Servindo o cozido
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd $DEV_PATH
            [ -e old-app ] && rm -rf old-app
            mv app old-app
            mv dist app
            wget -q --spider https://dona-fatima.duckdns.org
            if [ ! $? ]; then
              mv old-app app
            fi
