name: Cozinhando o Desenvolvimento

on:
  push:
    branches:
      - desenvolvimento
  workflow_dispatch:

jobs:
  cozinhando:
    name: Cozinhando para testar (build)
    runs-on: ubuntu-latest
    steps:
      - name: Sincronizando repositorio
        uses: actions/checkout@v4
        with:
          ref: desenvolvimento
      - name: Cozinhando (npm install & build)
        uses: actions/cache@v4
        with:
         path: |
           ~/.npm
           ${{ github.workspace }}/.next/cache
         key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
         restore-keys: |
           ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-
        run: |
          npm install
          npm run build --if-present
  deploy:
    name: Servindo para testar
    environment: Patio
    needs: cozinhando
    runs-on: ubuntu-latest
    steps:
      - name: Servindo o cozido
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd $DEV_PATH
            git checkout desenvolvimento
            git pull --rebase origin desenvolvimento
            cd ../caddy
            docker compose build pre-quintal
            docker compose up -d pre-quintal
