name: Cozinhando o Desenvolvimento

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  cozinhando:
    name: Cozinhando para validar (build)
    runs-on: ubuntu-latest
    steps:
      - name: Sincronizando repositorio
        uses: actions/checkout@v4
        with:
          ref: main
      - name: Preparando cache
        uses: actions/cache@v4
        with:
         path: |
           ~/.npm
           ${{ github.workspace }}/.next/cache
         key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
         restore-keys: |
           ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-
      - name: Cozinhando (npm install & build)
        run: |
          npm install --omit=dev
          npm run build --if-present
        env:
          GROQ_API_KEY: "some-key"
  deploy:
    name: Servindo em produção
    environment: Quintal
    needs: cozinhando
    runs-on: ubuntu-latest
    steps:
      - name: Servindo o cozido
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd $DEV_PATH
            git checkout main
            git pull --rebase origin main
            cd ../caddy
            docker compose up -d --build quintal
