name: Validando projeto
on:
  push:
    branches: ['*', '*/*', '**']
  pull_request:
    branches: ['*', '*/*', '**']
  workflow_dispatch:

jobs:
  build-and-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Atualizando codigo
        uses: actions/checkout@v4
      - name: Preparando Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Instala dependencias
        run: npm ci

      - name: Roda validação de lint
        run: npm run lint

      - name: Builda a aplicação
        run: npm run build
        env:
          CI: true
          GROQ_API_KEY: "some-key"

      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ runner.os }}
